# Generated by Django 3.2.5 on 2021-08-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210824_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Req',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='passowrd1',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='passowrd2',
            new_name='password2',
        ),
    ]
