# Generated by Django 3.2.5 on 2021-08-27 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210825_1224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Req',
        ),
    ]
