# Generated by Django 3.2.4 on 2022-08-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
